import dotenv from 'dotenv';

dotenv.config();

export const configs = {
  API_PORT: Number(process.env.API_PORT) || 3005,
  API_HOST: process.env.API_HOST,
  DB_URI: process.env.DB_URI,

  JWT_ACCESS_SECRET: process.env.JWT_ACCESS_SECRET,
  JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
  JWT_ACCESS_EXPIRES_IN: process.env.JWT_ACCESS_EXPIRES_IN,
  JWT_REFRESH_EXPIRES_IN: process.env.JWT_REFRESH_EXPIRES_IN,

  JWT_ACTION_FORGOT_PASSWORD_SECRET:
    process.env.JWT_ACTION_FORGOT_PASSWORD_SECRET,
  JWT_ACTION_FORGOT_PASSWORD_EXPIRES_IN:
    process.env.JWT_ACTION_FORGOT_PASSWORD_EXPIRES_IN,
  JWT_ACTION_VERIFY_EMAIL_SECRET: process.env.JWT_ACTION_VERIFY_EMAIL_SECRET,
  JWT_ACTION_VERIFY_EMAIL_EXPIRES_IN:
    process.env.JWT_ACTION_VERIFY_EMAIL_EXPIRES_IN,

  SMTP_EMAIL: process.env.SMTP_EMAIL,
  SMTP_PASSWORD: process.env.SMTP_PASSWORD,

  VERIFY_URL: process.env.VERIFY_URL,
};
